frontend/models/Article.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "article".
 *
 * @property integer $article_id
 * @property string $title
 * @property string $content
 * @property integer $status
 * @property integer $create_time
 * @property integer $update_time
 * @property integer $publish_time
 *
 * @property ArticleCategory[] $articleCategories
 * @property Category[] $categories
 */
class Article extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'article';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'status'], 'required'],
            [['content'], 'string'],
            [['status', 'create_time', 'update_time', 'publish_time'], 'integer'],
            [['title'], 'string', 'max' => 140],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'article_id' => 'Article ID',
            'title' => 'Title',
            'content' => 'Content',
            'status' => 'Status',
            'create_time' => 'Create Time',
            'update_time' => 'Update Time',
            'publish_time' => 'Publish Time',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getArticleCategories()
    {
        return $this->hasMany(ArticleCategory::className(), ['article_id' => 'article_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategories()
    {
        return $this->hasMany(Category::className(), ['id' => 'category_id'])->viaTable('article_category', ['article_id' => 'article_id']);
    }
}

backend/controllers/ArticleController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Article;
use backend\models\search\ArticleSearch;
use backend\components\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ArticleController implements the CRUD actions for Article model.
 */
class ArticleController extends Controller
{
    protected $something = '';
    
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return array_merge(parent::behaviors(), [
        ]);
            //Pruebas
            /*'access' => [
                'class' => \yii\filters\AccessControl::className(),
                //'only'=>...
                'rules'=>[
                    [
                        'allow'=>true,
                        'actions'=>['index', 'view', 'create', 'update', 'delete', 'publish'],
                        'roles'=>['?'] //Todos los roles, incluso usuarios no autenticados
                    ]
                ]
            ],*/
            /*
             * Cache del lado del cliente. No tiene sentido usarla en el backend
            'cache'=>[
                'class'=> \yii\filters\HttpCache::className(),
                //'only'=>['index'],
                'lastModified' => function ($action, $params) {
                    $q = new \yii\db\Query();                    
                    //return $q->from('article')->max('update_time');
                    return time();
                },
            ]*/
    }

    /**
     * Lists all Article models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ArticleSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Article model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Article model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Article();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->article_id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Article model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->article_id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }
    
    public function actionPublish($id)
    {
        $model = $this->findModel($id);
        
        if($model->setStatus(\backend\models\Article::STATUS_PUBLISHED)){
            $model->updateAttributes(['status']);
        }else{
            throw new \yii\web\HttpException(400, $model->getFirstError('status'));
        }
        
    }
    
    /**
     * Deletes an existing Article model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Article model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Article the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Article::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
         
    public function actionCategories($id = null)
    {
        if(isset($id)){
            $model = $this->findModel($id);
        }else{
            $model = new Article();            
        }
        return $this->renderAjax('_categories', ['model' => $model]);
    }
}

backend/controllers/CategoryController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Category;
use yii\data\ActiveDataProvider;
use backend\components\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use backend\models\search\CategorySearch;


/**
 * CategoryController implements the CRUD actions for Category model.
 */
class CategoryController extends Controller
{

    /**
     * Lists all Category models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CategorySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel, 
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Category model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Category model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Category();
        
        if(Yii::$app->request->isAjax){
            if ($model->load(Yii::$app->request->post()) ) {
                Yii::$app->response->format = yii\web\Response::FORMAT_JSON;
                
                if($model->save()){
                    return ['valid' => true];
                }else{                    
                    return ['valid' => false, 'errors'=>\yii\bootstrap\ActiveForm::validate($model)];
                }
            } else {
                return $this->renderAjax('create', [
                    'model' => $model,
                    'isAjax' => true
                ]);
            }
        }else{
            
            //Si no es por AJAX hago todo como siempre
            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                    'isAjax' => false
                ]);
            }
        }

    }
    
    /*
     * Función usada por el form de alta de categorias por ajax
     */
    public function actionValidate()
    {
        $model = new Category();
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post()) ) {
            Yii::$app->response->format = yii\web\Response::FORMAT_JSON;
            return \yii\bootstrap\ActiveForm::validate($model);
        }
        
    }
    
    //Version original
    /*public function actionCreate()
    {
        $model = new Category();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }*/


    /**
     * Updates an existing Category model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Category model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Category model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Category the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Category::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/controllers/ArticleController.php
<?php

namespace frontend\controllers;

use Yii;
use app\models\Article;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ArticleController implements the CRUD actions for Article model.
 */
class ArticleController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'pageCache' => [
                'class' => 'yii\filters\PageCache',
                'only' => ['index', 'view'],
                'duration' => 30,
//                'dependency' => [
//                    'class' => 'yii\caching\DbDependency',
//                    'sql' => 'SELECT COUNT(*) FROM post',
//                ],
                'variations' => [
                    Yii::$app->request->get()
                    //Yii::$app->request->get('page') //Si quiero que no cachee cuando le llega el parametro page por GET
                ]
            ],
        ];
    }
    
    /**
     * Lists all Article models.
     * @return mixed
     */
    public function actionIndex()
    {

        $dataProvider = new ActiveDataProvider([
            'query' => Article::find(),
            'pagination' => [
                'pageSize' => 4
            ]
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);

    }
    
    /**
     * Ejemplo de como implementar cache dentro del mismo controlador
     * Esto es util cuando por algun motivo no podemos implementarlo dentro del behavior
     */
    public function actionIndex_()
    {
        //$start = microtime(true);
        $cachedContent = Yii::$app->cache->get('article-index');
        
        if(!$cachedContent){
        
            $dataProvider = new ActiveDataProvider([
                'query' => Article::find(),
                'pagination' => [
                    'pageSize' => 4
                ]
            ]);

            $cachedContent = $this->render('index', [
                'dataProvider' => $dataProvider,
            ]);

            Yii::$app->cache->set('article-index', $cachedContent, 20);
        }/*else{
            echo "Hay contenido cacheado"; die;
        }*/
        
        //echo microtime(true) - $start;die;
        return $cachedContent;
    }

    /**
     * Displays a single Article model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Finds the Article model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Article the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Article::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/article/_categories.php
<?php

    use yii\bootstrap\Modal;
    use yii\helpers\Html;
    use yii\helpers\ArrayHelper;
    use yii\helpers\Url;
    use yii\widgets\ActiveForm;
    use yii\widgets\Pjax;

    use backend\models\Category;
?>

<fieldset>
    <?php $form = new ActiveForm(); ?>
    <?php

        Modal::begin([                    
            'header'=>'',
            'toggleButton'=>[ 
                'label'=>'', 
                'id' => 'addCategory',
                'value' => Url::to(['category/create']), 
                'tag'=>'span',
                'class'=>'glyphicon glyphicon-plus', 
                'role'=>'button',
            ]
        ]);

        echo "";

        Modal::end();

        $model->categories = [];

        foreach($model->tCategories as $cat){
            array_push($model->categories, $cat->id);
        }

        $fullList = Category::getFullList();
        $list = ArrayHelper::map($fullList, 'id', 'name');

        echo $form
                ->field($model, 'categories')
                ->label('Categories')
                ->checkboxList(
                    $list,
                    [
                        'separator'=>'<br>',
                        'item'=>function($index, $label, $name, $checked, $value){

                            $spaces = "";
                            //$level = $fullList[$value];   //No puedo acceder desde aca

                            $disable = false;
                            $checkbox = Html::checkbox($name, $checked, ['value' => $value, 'disabled' => $disable]);
                            return Html::label( $spaces .$checkbox . $label);
                        }
                    ]
                );

    ?>
</fieldset>

backend/views/article/_form.php
<?php

use yii\bootstrap\Modal;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\helpers\url;
use yii\widgets\ActiveForm;
use yii\widgets\Pjax;

use dosamigos\ckeditor\CKEditor;
use kartik\time\TimePicker;
use backend\models\Category;

/* @var $this yii\web\View */
/* @var $model backend\models\Article */
/* @var $form yii\widgets\ActiveForm */

?>

<div class="article-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'content')->widget( CKEditor::className(), 
        [
            'options'=>['rows' => 6],
            'preset'=>'basic'
        ]) ?>

    <?= $form->field($model, 'status')->dropDownList($model->getStatusList()) ?>

    <?= $form
            ->field($model, 'publish_time')
            ->widget(\yii\jui\DatePicker::classname(), 
            [
                'dateFormat'=>'dd-MM-yyyy', 
                'options'=>[
                    'class'=>'form-control'            
                ]
            ])
            ->label('Publish Date') ?>    
    
    <?= $form->field($model, 'publish_hour')->widget(TimePicker::classname(), []) ?>
        
    <div class="form-group" id="categories_container">
        <fieldset>
            <?php
                //Pjax::begin();

                    Modal::begin([                    
                        'header'=>'',
                        'id'=>'category-modal',
                        'toggleButton'=>[ 
                            'label'=>'', 
                            'id' => 'addCategory',
                            'value' => Url::to(['category/create']), 
                            'tag'=>'span',
                            'class'=>'glyphicon glyphicon-plus', 
                            'role'=>'button',
                        ]
                    ]);

                    echo "";

                    Modal::end();

                    $model->categories = [];

                    foreach($model->tCategories as $cat){
                        array_push($model->categories, $cat->id);
                    }

                    $fullList = Category::getFullList();
                    $list = ArrayHelper::map($fullList, 'id', 'name');

                    echo $form
                            ->field($model, 'categories')
                            ->label('Categories')
                            ->checkboxList(
                                $list,
                                [
                                    'separator'=>'<br>',
                                    'item'=>function($index, $label, $name, $checked, $value){

                                        $spaces = "";
                                        //$level = $fullList[$value];   //No puedo acceder desde aca

                                        $disable = false;
                                        $checkbox = Html::checkbox($name, $checked, ['value' => $value, 'disabled' => $disable]);
                                        return Html::label( $spaces .$checkbox . $label);
                                    }
                                ]
                            );

                    /*echo $form->field($model, 'categories')->hiddenInput(['value'=>'']);
                    echo "<ul>";
                    foreach($fullList as $cat)
                    {
                        $label = $cat["name"];
                        $checked = in_array($cat["id"], $model->categories);
                        $checkbox = Html::checkbox('Article[categories][]', $checked, ['value' =>$cat["id"]]);
                        echo Html::label($checkbox . $label, null, ["class"=>"col-xs-offset-" . $cat["level"] ]) . "<br>";

                        //Tira error "Array to string conversion" porque categories es un array
                        //echo $form->field($model, 'categories')->checkbox(['value'=>$cat["id"],'checked'=>$checked]);
                    }
                    echo "</ul>";           
                    */

                    echo '<div style="display:none;" ><a href="" id="update_categories" >Actualizar Lista</a>';
                //Pjax::end();
                
            ?>
        </fieldset>
    </div>
    
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>
    
    <?php ActiveForm::end(); ?>
    
    <script>
        var category = (function(){
            var instance = {};
            
            instance.init = function(){
                $(document).ready(function(){
                    
                    $(document).on('click', '#addCategory', function(event){
                        event.preventDefault();                        
                        $(".modal-body").load($(this).attr('value'));
                    });
                    
                    //$("#category-modal").on('hidden.bs.modal', function(){ //No usar esta sintaxis porque el modal puede ser pisado por pjax
                    $(document).on('hidden.bs.modal', "#category-modal", function(){
                        instance.reloadCategories();
                    });
                });
            }
            
            instance.reloadCategories = function(){
                var url = "<?php echo (isset($model->article_id))?Url::to(['article/categories', 'id'=>$model->article_id]): Url::to(['article/categories']); ?>";
                //Le agrego  #article-categories > * a la url para pisar el div contenedor
                $("#article-categories").load(url + " #article-categories > *"); 
                //$("#update_categories").trigger("click");
            }
            
            return instance;
        })();
        
    </script>
    
    <?php
        $js = 'category.init()';
        $this->registerJs($js);
    ?>
    
</div>

backend/views/article/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\search\ArticleSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="article-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'article_id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'content') ?>

    <?= $form->field($model, 'status') ?>

    <?= $form->field($model, 'create_time') ?>

    <?php // echo $form->field($model, 'update_time') ?>

    <?php // echo $form->field($model, 'publish_time') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/article/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\models\Article */

$this->title = 'Create Article';
$this->params['breadcrumbs'][] = ['label' => 'Articles', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="article-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/article/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;


/* @var $this yii\web\View */
/* @var $searchModel backend\models\search\ArticleSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Articles';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="article-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Article', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'article_id',
            'title',
            'content:ntext',
            [
                'attribute'=>'status',
                'value'=>function($data){
                    return $data->getStatus($data->status);
                },
                'filter'=>$searchModel->getStatusList()
            ],
            [
                'attribute'=>'category_id',
                'value'=>function($data){
                    $names = "";
                    foreach($data->tCategories as $i => $category){                        
                        $url = '?r=article/index&ArticleSearch[category_id]=' . $category->id;
                        $names .= Html::a($category->name, $url) . (( $i < count($data->tCategories) - 1 )? ", " : "");
                    }
                    return $names;
                },
                'format'=>'raw',
                'filter'=>yii\helpers\ArrayHelper::map(\backend\models\Category::getForDropDown(), 'id', 'name'),
                'contentOptions'=>[
                    'style'=>'max-width: 100px; word-break: break-all; white-space: normal'
                ]
            ],
            //'create_time:datetime',
            ['class' => 'yii\grid\ActionColumn'],
            [
                'class'=>'yii\grid\ActionColumn', 
                'template'=>'{publish}', 
                'buttons'=>[
                    'publish'=>function($url, $model, $key){
                        //TODO: La validacion de estado esta bien pero habria que unificarla con la del modelo
                        /*return ($model->status != \backend\models\Article::STATUS_PUBLISHED)? Html::a('Publish', $url, ['title'=>'Publish','class'=>'article_publish']): "";*/

                        return 
                            ($model->status != \backend\models\Article::STATUS_PUBLISHED)? 
                                \app\components\publishbutton\PublishButton::widget(['url' => $url]): 
                                "";
                    }                    
                ]   
            ]
                        
        ],
    ]); ?>
</div>


<?php

    //$js = 'article.init()';
    //$this->registerJs($js);

?>

backend/views/article/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\Article */

$this->title = 'Update Article: ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Articles', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->article_id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="article-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/article/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\models\Article */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Articles', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="article-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->article_id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->article_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'article_id',
            'title',
            'content:ntext',
            [
              'label'=>$model->getAttributeLabel('status'),
              'value'=>$model->getStatus($model->status)
            ],
            'create_time:datetime',
            'update_time:datetime',
            'publish_time:datetime',
            [
                'label'=>'Categories',
                'value'=>function($model)
                {
                    $cats = "";
                    foreach($model->tCategories as $i => $cat)
                    {
                        
                        $cats.= $cat->name . ( ( $i < count($model->tCategories) - 1 )? ", ": "" ) ;
                    }
                    return $cats;
                }
            ]
        ],
    ]) ?>

</div>