backend/models/Category.php
<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "category".
 *
 * @property integer $id
 * @property string $name
 * @property integer $status
 * @property integer $category_id
 *
 * @property ArticleCategory[] $articleCategories
 * @property Category $category
 * @property Category[] $categories
 */
class Category extends \yii\db\ActiveRecord
{
    const STATUS_ENABLED = 1;
    const STATUS_DISABLED = 2;
    
    private $statusList = [
        self::STATUS_ENABLED=>"Enabled",
        self::STATUS_DISABLED=>"Disabled"
    ];
    
    //private $list = [];
    //private $fullList = [];
    
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'category';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'status'], 'required'],
            [['status', 'category_id'], 'integer'],
            [['name'], 'string', 'max' => 200],
            [['category_id'], 'exist', 'skipOnError' => true, 'targetClass' => Category::className(), 'targetAttribute' => ['category_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'status' => 'Status',
            'category_id' => 'Parent Category',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getArticleCategories()
    {
        return $this->hasMany(ArticleCategory::className(), ['category_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(Category::className(), ['id' => 'category_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategories()
    {
        return $this->hasMany(Category::className(), ['category_id' => 'id']);
    }
    
    //Funciones propias
    public function getStatusList()
    {
        return $this->statusList;
    }
    
    public function getStatus($code)
    {
        return (isset($this->statusList[$code]))? $this->statusList[$code]: null;
    }
    
    public static function getForDropDown($id = null)
    {
        $nodes = null;
        if(isset($id)){
            $nodes = self::find()->where("id!=" . $id)->orderBy('name')->all();
        }else{
            $nodes = self::find()->orderBy('name')->all();
        }
        
        $tree = self::getTree($nodes);

        $list = [];

        self::loadTreeItems($tree, 0, $list);

        return $list;
    }
    
    /*
     * Devuelve una lista anidada de categorías a partir de una lista devuelta por ActiveRecord
     */
    private function getTree($nodes) 
    {
        $refs = array();
        $list = array();

        foreach ($nodes as $data) {
            $thisref = &$refs[ $data['id'] ];
            $thisref['category_id'] = $data['category_id'];
            $thisref['text'] = $data['name'];
            if ($data['category_id'] == 0) {
                $list[ $data['id'] ] = &$thisref;
            } else {
                $refs[ $data['category_id'] ]['children'][ $data['id'] ] = &$thisref;
            }   
        }           
        return $list;
    }

    /*
     * Funcion recursiva para cargar una array plano de categorías con el formato: array("id"=>$key, "name"=>$name)
     * @tree: lista de listas 
     * @level: entero que indica el nivel de jerarquía
     * @list: array por referencia
     */
    private function loadTreeItems($tree, $level, &$list)
    {
        foreach($tree as $key => $item)
        {

            $name = $item["text"];
            for($i = 0; $i < $level; $i++)
            {
                $name = "-" . $name;
            }

            array_push($list, array("id"=>$key, "name"=>$name));

            if(isset($item["children"]))
            {
                $nextlevel = $level + 1;
                self::loadTreeItems($item["children"], $nextlevel, $list);
            }

        }
    }    

    /*
     * Función estática recursiva que carga una lista con todas las categorias y un campo level que es el nivel de anidamiento
     */
    private static function loadFullList($tree, $level, &$fullList)
    {
        foreach($tree as $key => $item)
        {

            array_push($fullList, array("id"=>$key, "name"=>$item["text"], "level"=>$level));

            if(isset($item["children"]))
            {
                $nextlevel = $level + 1;
                self::loadFullList($item["children"], $nextlevel, $fullList);
            }

        }
    }

    /*
     * Devuelve lista de categorias con nivel de anidamiento
     * Ya no uso una propiedad del objeto para poder llamar a esta funcion desde una vista sin tener que crear una instancia del objeto
     */
    public static function getFullList()
    {
        $fullList = [];

        self::loadFullList(self::getTree( self::find()->orderBy('name')->all() ), 0, $fullList);

        return $fullList;
    }
    
}

frontend/models/Category.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "category".
 *
 * @property integer $id
 * @property string $name
 * @property integer $status
 * @property integer $category_id
 *
 * @property ArticleCategory[] $articleCategories
 * @property Article[] $articles
 * @property Category $category
 * @property Category[] $categories
 */
class Category extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'category';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'status'], 'required'],
            [['status', 'category_id'], 'integer'],
            [['name'], 'string', 'max' => 200],
            [['category_id'], 'exist', 'skipOnError' => true, 'targetClass' => Category::className(), 'targetAttribute' => ['category_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'status' => 'Status',
            'category_id' => 'Category ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getArticleCategories()
    {
        return $this->hasMany(ArticleCategory::className(), ['category_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getArticles()
    {
        return $this->hasMany(Article::className(), ['article_id' => 'article_id'])->viaTable('article_category', ['category_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(Category::className(), ['id' => 'category_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategories()
    {
        return $this->hasMany(Category::className(), ['category_id' => 'id']);
    }
}

backend/controllers/CategoryController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Category;
use yii\data\ActiveDataProvider;
use backend\components\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use backend\models\search\CategorySearch;


/**
 * CategoryController implements the CRUD actions for Category model.
 */
class CategoryController extends Controller
{

    /**
     * Lists all Category models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CategorySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel, 
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Category model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Category model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Category();
        
        if(Yii::$app->request->isAjax){
            if ($model->load(Yii::$app->request->post()) ) {
                Yii::$app->response->format = yii\web\Response::FORMAT_JSON;
                
                if($model->save()){
                    return ['valid' => true];
                }else{                    
                    return ['valid' => false, 'errors'=>\yii\bootstrap\ActiveForm::validate($model)];
                }
            } else {
                return $this->renderAjax('create', [
                    'model' => $model,
                    'isAjax' => true
                ]);
            }
        }else{
            
            //Si no es por AJAX hago todo como siempre
            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                    'isAjax' => false
                ]);
            }
        }

    }
    
    /*
     * Función usada por el form de alta de categorias por ajax
     */
    public function actionValidate()
    {
        $model = new Category();
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post()) ) {
            Yii::$app->response->format = yii\web\Response::FORMAT_JSON;
            return \yii\bootstrap\ActiveForm::validate($model);
        }
        
    }
    
    //Version original
    /*public function actionCreate()
    {
        $model = new Category();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }*/


    /**
     * Updates an existing Category model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Category model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Category model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Category the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Category::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/controllers/CategoryController.php
<?php

namespace frontend\controllers;

use Yii;
use app\models\Category;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CategoryController implements the CRUD actions for Category model.
 */
class CategoryController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'pageCache' =>[
                'class'=>'yii\filters\PageCache',
                'only'=>['index', 'view'], //Solo cacheamos index y view (no usar con create y update porque no guardaria los cambios en caso de necesitarlos)
                'duration'=>30,
                'variations'=>[
                    Yii::$app->request->get()
                ]
            ]
        ];
    }

    /**
     * Lists all Category models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Category::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Category model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Category model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Category();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Category model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Category model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Category model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Category the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Category::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/category/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\Category */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="category-form">

    <?php $form = ActiveForm::begin([
        'id'=>'category_form', 
        'enableClientValidation'=>true, //Descomentar esta linea para probar validacion del lado del servidor
        'enableAjaxValidation'=>false,
        'validationUrl'=>Url::to(['category/validate'])
    ]); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'status')->dropDownList($model->getStatusList()) ?>
    
    <?= $form->field($model, 'category_id')->dropDownList(yii\helpers\ArrayHelper::map($model->getForDropDown($model->id), 'id', 'name'), ['prompt'=>'Choose a category']) ?>
    
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<script>

var category_form = (function(){
    var instance = {}
    
    instance.init = function(){
        $(document).ready(function(){
            $('#category_form')
            .on('beforeSubmit', function(event){
                
                event.preventDefault(); //Evito que haga dos llamadas AJAX si tengo habilitada la validación por AJAX
        
                var form = $(this);
                var formData = form.serialize();
                $.ajax({
                    type: form.attr('method'),
                    url: form.attr('action'),
                    data: formData,
                    success: function(data){ 
                        console.log("Callback");
                        console.log(data);
                        if(data.valid){
                            //Cierro modal - TODO: buscar la forma mas correcta de hacerlo
                            //$("#addCategory").trigger('click');
                            //Otras forma
                            $("#category-modal").modal('hide');
                            toastr.success('La categoría se guardó correctamente', 'Alta categoría');
                        }else{
                            $('#category_form').yiiActiveForm('updateMessages', data.errors, true);
                        }
                        
                    },
                    error: function(error){
                        console.log(error);
                        toastr.error('Hubo un error al intentar guardar la categoría', 'Alta categoría');
                    }
                });
                
                return false;
            })
            .on('submit', function(event){
                event.preventDefault();
            })
        })
    };
    
    return instance;
})();
</script>

<?php
    if(Yii::$app->request->isAjax){
        $js = 'category_form.init()';
        $this->registerJs($js);
    }
?>

backend/views/category/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\search\CategorySearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="category-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'status') ?>

    <?= $form->field($model, 'category_id') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/category/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Category */

$this->title = 'Create Category';
$this->params['breadcrumbs'][] = ['label' => 'Categories', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="category-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/category/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Categories';
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="category-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Category', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'name',
            [
                'attribute' => 'status',     
                'value'=>function($data){
                    //Puedo hacer $data->[una_funcion_del_modelo]
                    return $data->getStatus($data->status);
                },
                'filter'=>$searchModel->getStatusList()
            ],
            [
                'attribute'=>'category_id',
                'value'=>'category.name',
                'filter'=>yii\helpers\ArrayHelper::map($searchModel->getForDropDown(), 'id', 'name')
            ],       

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

backend/views/category/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Category */

$this->title = 'Update Category: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Categories', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="category-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/category/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Category */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Categories', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="category-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            [
                'label'=>$model->getAttributeLabel('status'),
                'value'=>$model->getStatus($model->status)
            ],
            [
                'label'=>$model->getAttributeLabel('category_id'),
                'value'=>($model->category)? $model->category->name: ""
            ]
        ],
    ]) ?>

</div>

<hr>

<!--Pruebas con qrcode-library-->
<?php
//use Da\QrCode\QrCode;
$qrCode = (new \Da\QrCode\QrCode('This is my text........................................................'))
    ->setSize(250)
    ->setMargin(5)
    ->useForegroundColor(51, 153, 255);
echo '<img src="' . $qrCode->writeDataUri() . '">';
?>